### ISSUE TITLE
InvalidIndexError: Reindexing only valid with uniquely valued Index objects

### ISSUE THREAD

**Issue by oussamachaab** [sna-hm/hybrid-dlm#1]
how can we slove this

**Comment by sna-hm** [comment]
It might be due to some duplicate columns. First, check your dataset; if it contains some duplicate columns, reseting the index does not work. Therefore, duplicated columns should be removed first to make it works. If you can share the used dataset and screenshot of the given error, it might be helpful for me to provide a specific solution for this.

**Comment by oussamachaab** [comment]
It's the same one that you use in your project

**Comment by sna-hm** [comment]
The issue is fixed and tested. You can get the updated code for a new attempt. The latest source is tested on Python 3.7.6 and Tensorflow version 2.1.0 with Keras 2.3.1 environment. If it is not working yet, please list the followed steps to reproduce. 

Thank You.

**Comment by jerrynewnguyen28** [comment]
Hi author, I've had trouble with pandas:

Traceback (most recent call last):
  File "C:\Users\ACER\OneDrive\Desktop\HybridDLM-main\train.py", line 82, in <module>
    train = create_scaler(pd.concat([legitimate_train, phish_train], axis=0)).sample(frac=1).reset_index(drop=True)
  File "C:\Users\ACER\OneDrive\Desktop\HybridDLM-main\train.py", line 35, in create_scaler
    df = pd.concat([df.drop(columns=['html_length','n_hyperlinks','n_script_tag','n_link_tag','n_comment_tag']),
  File "C:\Program Files\Python310\lib\site-packages\pandas\util\_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\pandas\core\reshape\concat.py", line 382, in concat
    return op.get_result()
  File "C:\Program Files\Python310\lib\site-packages\pandas\core\reshape\concat.py", line 613, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
  File "C:\Program Files\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3902, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects

I've used python 3.10.4, TensorFlow and Keras version 2.10.0, Pandas version 1.5.0. I exported requirements by pipreqs tool but same failure. Can you give the exact version of the packages?
Have a nice day!!!
